echo:
  level: DEBUG
repo_files:
  exclude_file_patterns:
  - .idea/
  ignored_file_extensions:
  - .pyc
  - .drawio
  - .png
  - .jpg
  max_file_size: 1000000
telemetry:
  api_url: https://log-api.newrelic.com/log/v1
scan_patterns:
  custom_scan_patterns:
  - test