FROM debian
WORKDIR app

# Install deps
RUN apt-get update && apt-get autoclean && \
    apt-get install -y -q --allow-unauthenticated \
    git curl sudo build-essential

# Install ca-certificates
RUN apt-get install -y ca-certificates
COPY ./ca-certificates* /app/ca-certificates
RUN cp /app/ca-certificates/*.crt /usr/local/share/ca-certificates | true && update-ca-certificates

# set up dirs
RUN useradd -m -s /bin/bash linuxbrew && \
    usermod -aG sudo linuxbrew &&  \
    mkdir -p /home/linuxbrew/.linuxbrew && \
    chown -R linuxbrew: /home/linuxbrew/.linuxbrew

RUN /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
ENV PATH="/home/linuxbrew/.linuxbrew/bin:${PATH}"
RUN brew tap slalombuild/secureli
RUN brew install secureli
RUN git clone https://github.com/pypa/pip pip
WORKDIR pip
RUN secureli init --yes
RUN secureli scan --mode all-files
