FROM debian
WORKDIR app
ARG mytoken
#ENV HOMEBREW_GITHUB_API_TOKEN=$mytoken

# Install deps
RUN apt-get update && apt-get autoclean && \
    apt-get install -y -q software-properties-common gnupg

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 23F3D4EA75716059
RUN apt-add-repository https://cli.github.com/packages
RUN apt-get update

RUN  apt-get install -y -q --allow-unauthenticated gh python3-pip

RUN pip3 --version && pip3 install secureli

RUN git clone https://github.com/pypa/pip pip
WORKDIR pip
RUN secureli init --yes
RUN secureli scan  --mode all-files
