# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# These jobs are specifically designed to test the codebase
# and ensure that basic contributing from both mac and windows will work

name: Build & Test

on:
  push:
    branches-ignore: [ main ]
  workflow_call:


jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set Up Project
        run: |
          pip install poetry
          poetry install

      - name: Run Tests
        run: |
          poetry run poe precommit
        # Both of these lines error when run on a windows image, more research required as to why
          # poetry run poe coverage
          # poetry run secureli build


  build-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Branch name
        run: ./scripts/get-current-branch.sh

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Set Up Project
        run: |
          pip install poetry
          poetry install

      - name: Run Tests
        run: |
          poetry run poe precommit
          poetry run poe coverage
          poetry run secureli build


  secureli-release-noop:
    name: Release Test
    needs: [ build-linux, build-windows ]
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          root_options: -vv --noop
