# This workflow pulls the published seCureLI packages from Pypi & Homebrew & executes them against a test repo
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Integration Testing

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install seCureLI
        # Note that this is a powershell script
        run: |
          pip3 --version
          pip3 install secureli
          git clone https://github.com/pypa/pip pip
          cd pip
          secureli init --yes

      - name: seCureLI Scan
        run: |
          cd pip
          $ErrorActionPreference = 'SilentlyContinue'
          secureli scan --mode all-files --yes
          $LastExitCode = 0  # Force exit code to 0 to avoid failing the build since scan returns nonzero exit status


  test-homebrew-osx:
    runs-on: macos-latest
    steps:
      - name: Test with Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Prep for python 3.11.3 install # Removes python 3.11.3 to avoid conflict with homebrew python
        run: |
          rm -rf '/usr/local/bin/2to3'
          rm -rf '/usr/local/bin/2to3-3.11'
          rm -rf '/usr/local/bin/idle3'
          rm -rf '/usr/local/bin/idle3.11'
          rm -rf '/usr/local/bin/pydoc3'
          rm -rf '/usr/local/bin/pydoc3.11'
          rm -rf '/usr/local/bin/python3'
          rm -rf '/usr/local/bin/python3-config'
          rm -rf '/usr/local/bin/python3.11'
          rm -rf '/usr/local/bin/python3.11-config'

      - name: Set up seCureLI
        run: |
          brew tap slalombuild/secureli
          HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install secureli

      - name: Checkout test repo
        uses: actions/checkout@v4
        with:
          repository: pypa/pip
          path: pip

      - name: Init seCureLI
        run: cd pip && secureli init --yes && secureli scan


  test-pypi-osx:
    runs-on: macos-latest
    steps:
      - name: Test with Pypi
        run: |
          pip3 --version #what do we have on the macos image
          pip3 install secureli
          git clone https://github.com/pypa/pip pip
          cd pip
          secureli init --yes
          secureli scan  --mode all-files --yes
