# This lints PR titles to ensure they follow semver title conventions. This allows semver to know what kind of patch to create
name: PR Title Lint

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: Slashgear/action-check-pr-title@v4.3.0
      with:
        regexp: "(chore|style|test|feat|fix|docs): .++" # Regex the title should match.
        helpMessage: "Example: 'feat: example of title'"
