# This lints PR titles to ensure they follow semver title conventions. This allows semver to know what kind of patch to create
name: PR Title Lint

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - edited
      - reopened

jobs:
  check_pr_title:
    runs-on: ubuntu-latest
    steps:
    - uses: morrisoncole/pr-lint-action@v1.7.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        title-regex: "(chore|style|test|feat|fix|docs): .+"
        on-failed-regex-fail-action: true
