name: Testing Publish Workflow

on:
  push:
    branches: [ feature/secureli-275-secure-tokens ]


jobs:
  build-test:
    name: Build & Test
    uses: ./build_and_test.yml


  next_job:
    name: Next Job
    needs: [ build-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Get App Token
        uses: tibdex/github-app-token@v1
        id: app_token
        with:
          app_id: 360953
          private_key: ${{ secrets.ACTIONHELPER }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}
