name: secureliCD

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest
    needs: secureliCI
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Checkout Secureli Homebrew Repo
      uses: actions/checkout@v3
      with:
        repository: slalombuild/homebrew-secureli
        token: ${{ secrets.ADMIN_TOKEN_SASCHA }} # `GH_PAT` is a secret that contains your PAT
        path: homebrew-secureli
    - name: Homebrew Formula Generation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        GH_TOKEN: ${{ secrets.ADMIN_TOKEN_SASCHA }}
      run: |
        poetry build
        export secureliVersion=$(poetry version | awk '{print $2}')
        export secureliSha256=$(sha256sum dist/secureli-${secureliVersion}.tar.gz | awk '{print $1}')
        git config --global user.email "secureli-automation@slalom.com"
        git config --global user.name "Secureli Automation"
        pip install requests jinja2
        python ./scripts/get-secureli-dependencies.py
        cd homebrew-secureli
        git checkout -b "secureli-${secureliVersion}-formula-generation"
        git add ./Formula/secureli.rb
        git commit -m "Creating pull request with latest Secureli formula for version ${secureliVersion}"
        git push origin secureli-${secureliVersion}-formula-generation --repo https://github.com/slalombuild/homebrew-secureli.git
        gh pr create --title "Secureli Formula Automated Creation for version ${secureliVersion}" --body "Automated formula creation"

    - name: Upload binaries to release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
